const APP_ID='homeledger',VERSION=1,KEY='homeledger:v1',MAX_ITEMS=40,MAX_STATE=24000;
const areas=['Inside','Outside','Safety','Appliances','Utilities','Other'],intervals=[1,3,6,12,24];
const $=s=>document.querySelector(s), today=()=>new Date().toISOString().slice(0,10);
const blank=()=>({name:'',area:'Inside',interval:3,lastDone:'',note:''});
const validDate=v=>v===''||(/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00Z'))&&v<=today());
const validItem=x=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length===6&&typeof x.id==='string'&&x.id.length>0&&x.id.length<50&&typeof x.name==='string'&&x.name.trim()&&x.name.length<=80&&areas.includes(x.area)&&intervals.includes(Number(x.interval))&&validDate(x.lastDone)&&typeof x.note==='string'&&x.note.length<=120;
const validState=x=>x&&typeof x==='object'&&!Array.isArray(x)&&Object.keys(x).length===3&&x.app===APP_ID&&x.version===VERSION&&Array.isArray(x.items)&&x.items.length<=MAX_ITEMS&&new Set(x.items.map(i=>i.id)).size===x.items.length&&x.items.every(validItem)&&JSON.stringify(x).length<=MAX_STATE;
const empty=()=>({app:APP_ID,version:VERSION,items:[]});
function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'null');return validState(x)?x:empty();}catch{return empty();}}
let state=load();
function persist(next){const raw=JSON.stringify(next);if(raw.length>MAX_STATE)throw Error('too large');localStorage.setItem(KEY,raw);state=next;}
function addMonths(date,n){if(!date)return '';const d=new Date(date+'T00:00:00Z'), day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+Number(n));const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10);}
function due(item){return item.lastDone?addMonths(item.lastDone,item.interval):'';}
function status(item){const d=due(item);if(!d)return ['baseline','Needs baseline'];if(d<today())return ['overdue','Overdue'];if(d===today())return ['today','Due today'];return ['later','Due '+d];}
function text(tag,cls,value){const n=document.createElement(tag);if(cls)n.className=cls;n.textContent=value;return n;}
function download(name,data){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'application/json'}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function formItem(){const f=$('#itemForm');return {name:f.name.value.trim(),area:f.area.value,interval:Number(f.interval.value),lastDone:f.lastDone.value,note:f.note.value.trim()};}
function fill(x){const f=$('#itemForm');Object.keys(x).forEach(k=>{if(f.elements[k])f.elements[k].value=x[k];});}
function render(){const box=$('#ledgerView');box.replaceChildren();$('#count').textContent=state.items.length;if(!state.items.length){box.append(text('p','muted','Your ledger stays in this browser until you add a job.'));$('#nextMove').replaceChildren(text('p','muted','Add a job and the ledger will surface what to look at first.'));return;}
 const rank={overdue:0,today:1,baseline:2,later:3};const sorted=[...state.items].sort((a,b)=>rank[status(a)[0]]-rank[status(b)[0]]||(due(a)||'9999').localeCompare(due(b)||'9999')||a.name.localeCompare(b.name));const first=sorted[0],fs=status(first);const next=document.createElement('div');next.className='next-callout';next.append(text('span','mini-label','START HERE'),text('strong',null,first.name),text('p',null,fs[1]+(first.lastDone?' · last done '+first.lastDone:' · add a baseline date')));$('#nextMove').replaceChildren(next);
 const list=document.createElement('div');list.className='queue-list';sorted.forEach(item=>{const st=status(item),article=document.createElement('article');article.className='queue-item';const head=document.createElement('div');head.className='queue-head';head.append(text('h3',null,item.name),text('span','priority '+st[0],st[1]));const meta=text('p','meta',item.area+' · every '+item.interval+' month'+(item.interval===1?'':'s')+(item.lastDone?' · last done '+item.lastDone:' · no baseline date')+(item.note?' · '+item.note:''));const actions=document.createElement('div');actions.className='item-actions';const done=document.createElement('button');done.type='button';done.className='secondary';done.textContent='Mark complete today';done.setAttribute('aria-label','Mark '+item.name+' complete today');done.addEventListener('click',()=>{try{persist({app:APP_ID,version:VERSION,items:state.items.map(x=>x.id===item.id?{...x,lastDone:today()}:x)});render();$('#formStatus').textContent=item.name+' marked complete. Next review recalculated.';}catch{alert('Could not update the local ledger. Existing data is unchanged.');}});const remove=document.createElement('button');remove.type='button';remove.className='remove';remove.textContent='Remove';remove.setAttribute('aria-label','Remove '+item.name);remove.addEventListener('click',()=>{if(confirm('Remove '+item.name+' from this browser?'))try{persist({app:APP_ID,version:VERSION,items:state.items.filter(x=>x.id!==item.id)});render();}catch{alert('Could not update the local ledger.');}});actions.append(done,remove);article.append(head,meta,actions);list.append(article);});box.append(list);}
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const raw=formItem(),item={...raw,id:crypto.randomUUID?crypto.randomUUID():String(Date.now())};if(!raw.name||!validItem(item)){$('#formStatus').textContent='Add a name and check the fields before saving.';return;}if(state.items.length>=MAX_ITEMS){$('#formStatus').textContent='The ledger is full. Export or remove an item first.';return;}try{persist({app:APP_ID,version:VERSION,items:[...state.items,item]});fill(blank());$('#formStatus').textContent='Added locally. Your next review is shown below.';render();$('#ledger').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'nearest'});}catch{$('#formStatus').textContent='This browser could not save. Existing data is unchanged.';}});
$('#resetForm').addEventListener('click',()=>{fill(blank());$('#formStatus').textContent='';});
$('#clearLedger').addEventListener('click',()=>{if(state.items.length&&confirm('Clear every HomeLedger item from this browser?'))try{persist(empty());render();}catch{alert('Could not clear the ledger.');}});
$('#exportLedger').addEventListener('click',()=>state.items.length?download('homeledger.json',JSON.stringify(state,null,2)):alert('Add a job before exporting.'));
$('#importLedger').addEventListener('change',e=>{const file=e.target.files[0];e.target.value='';if(!file||file.size>MAX_STATE*2){alert('Import rejected: file is too large. Existing data is unchanged.');return;}const reader=new FileReader();reader.onload=()=>{try{const x=JSON.parse(reader.result);if(!validState(x))throw Error('invalid');persist(x);render();$('#formStatus').textContent='Imported locally.';}catch{alert('Import rejected. Use an unmodified HomeLedger export. Existing data is unchanged.');}};reader.readAsText(file);});
$('#printLedger').addEventListener('click',()=>state.items.length?window.print():alert('Add a job before printing.'));fill(blank());render();